# Generated by Django 4.1.7 on 2023-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("dis_price", models.FloatField()),
                ("category", models.CharField(max_length=100)),
                ("descrip", models.TextField()),
                ("image", models.CharField(max_length=100)),
            ],
        ),
    ]
